/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIDemo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SIOW HAN BIN
 */
public class editToDoForm extends javax.swing.JFrame {

    /**
     * Creates new form editToDoForm
     */
    private static String todo = "";
    private static String status = "";
    public editToDoForm() {
        initComponents();
        editToDoTxt.setText(editToDoForm.todo);
        editStatusCbx.setSelectedItem(editToDoForm.status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editToDoTxt = new javax.swing.JTextField();
        editStatusCbx = new javax.swing.JComboBox<>();
        updateToDo = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editToDoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editToDoTxtActionPerformed(evt);
            }
        });

        editStatusCbx.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editStatusCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not stated", "In Progress", "Done" }));

        updateToDo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        updateToDo.setText("Update");
        updateToDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToDoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Status");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Edit Todo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("To Do");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editToDoTxt)
                            .addComponent(editStatusCbx, 0, 311, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(updateToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(editToDoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editStatusCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(updateToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editToDoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editToDoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editToDoTxtActionPerformed

    private void updateToDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToDoActionPerformed
        try {
            // TODO add your handling code here:
            
            //read the existing todo records from the file
            FileReader fr = new FileReader("todo.txt");
            BufferedReader br = new BufferedReader(fr);
            LoginForm login = new LoginForm(); //gets the logged-in user's info
            String read;
            //Using ArrayList to store records read from the file
            ArrayList <ArrayList<String>>todo = new ArrayList<>();
            //Reading each line from the file
            while((read = br.readLine()) !=null){
                ArrayList <String> record = new ArrayList<>();
                //store each part of the line in an arraylist
                record.add(read.split(";")[0]);
                record.add(read.split(";")[1]);
                record.add(read.split(";")[2]);
                record.add(read.split(";")[3]);
                todo.add(record);
            }
            br.close();
            
            for(int i = 0;i< todo.size();i++){
                ArrayList<String> record = todo.get(i);
                if (login.getusername().equals(
                    record.get(3)) && editToDoForm.todo.equals(record.get(0))){
                record.set(0,editToDoTxt.getText());
                record.set(0,editStatusCbx.getSelectedItem().toString());
                break;
                
            }
            }
            //Writing the updated TODO records back to the file
            FileWriter fw = new FileWriter("todo.txt");
            for (int i = 0 ; i< todo.size();i++){
             fw.write(todo.get(i).get(0)+";");    
             fw.write(todo.get(i).get(1)+";");    
             fw.write(todo.get(i).get(2)+";");    
             fw.write(todo.get(i).get(3)+";\n");    
        }
        fw.close();
        //close the current window and open the todo list view
        this.dispose();
        new toDoListForm().setVisible(true);
}catch (IOException e) {
            System.out.println("Exception:"+e.getMessage());
}
    }//GEN-LAST:event_updateToDoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editToDoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editToDoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editToDoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editToDoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editToDoForm().setVisible(true);
            }
        });
    }

    void setDataForm(String todo, String status) {
        editToDoForm.todo = todo;
        editToDoForm.status = status;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> editStatusCbx;
    private javax.swing.JTextField editToDoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton updateToDo;
    // End of variables declaration//GEN-END:variables
}
